# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nfp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nfp.proto',
  package='helloworld',
  syntax='proto3',
  serialized_pb=_b('\n\tnfp.proto\x12\nhelloworld\"-\n\nNfpRequest\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x1e\n\x0bNfpResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2S\n\x03Nfp\x12L\n\x17\x63reate_network_function\x12\x16.helloworld.NfpRequest\x1a\x17.helloworld.NfpResponse\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_NFPREQUEST = _descriptor.Descriptor(
  name='NfpRequest',
  full_name='helloworld.NfpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='helloworld.NfpRequest.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='helloworld.NfpRequest.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=70,
)


_NFPRESPONSE = _descriptor.Descriptor(
  name='NfpResponse',
  full_name='helloworld.NfpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='helloworld.NfpResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['NfpRequest'] = _NFPREQUEST
DESCRIPTOR.message_types_by_name['NfpResponse'] = _NFPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NfpRequest = _reflection.GeneratedProtocolMessageType('NfpRequest', (_message.Message,), dict(
  DESCRIPTOR = _NFPREQUEST,
  __module__ = 'nfp_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.NfpRequest)
  ))
_sym_db.RegisterMessage(NfpRequest)

NfpResponse = _reflection.GeneratedProtocolMessageType('NfpResponse', (_message.Message,), dict(
  DESCRIPTOR = _NFPRESPONSE,
  __module__ = 'nfp_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.NfpResponse)
  ))
_sym_db.RegisterMessage(NfpResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'))

_NFP = _descriptor.ServiceDescriptor(
  name='Nfp',
  full_name='helloworld.Nfp',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=104,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_network_function',
    full_name='helloworld.Nfp.create_network_function',
    index=0,
    containing_service=None,
    input_type=_NFPREQUEST,
    output_type=_NFPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NFP)

DESCRIPTOR.services_by_name['Nfp'] = _NFP

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class NfpStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.create_network_function = channel.unary_unary(
          '/helloworld.Nfp/create_network_function',
          request_serializer=NfpRequest.SerializeToString,
          response_deserializer=NfpResponse.FromString,
          )


  class NfpServicer(object):
    """The greeting service definition.
    """

    def create_network_function(self, request, context):
      """Sends a greeting
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_NfpServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'create_network_function': grpc.unary_unary_rpc_method_handler(
            servicer.create_network_function,
            request_deserializer=NfpRequest.FromString,
            response_serializer=NfpResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'helloworld.Nfp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaNfpServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def create_network_function(self, request, context):
      """Sends a greeting
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaNfpStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def create_network_function(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends a greeting
      """
      raise NotImplementedError()
    create_network_function.future = None


  def beta_create_Nfp_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('helloworld.Nfp', 'create_network_function'): NfpRequest.FromString,
    }
    response_serializers = {
      ('helloworld.Nfp', 'create_network_function'): NfpResponse.SerializeToString,
    }
    method_implementations = {
      ('helloworld.Nfp', 'create_network_function'): face_utilities.unary_unary_inline(servicer.create_network_function),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Nfp_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('helloworld.Nfp', 'create_network_function'): NfpRequest.SerializeToString,
    }
    response_deserializers = {
      ('helloworld.Nfp', 'create_network_function'): NfpResponse.FromString,
    }
    cardinalities = {
      'create_network_function': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'helloworld.Nfp', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
